### ISSUE TITLE
Question about macvlan for multiple AD

### ISSUE THREAD

**Issue by killmasta93** [diegogslomp/samba-ad-dc#14]
Hi
I was testing out macvlan, on my linux host because i wanted to see if i can have 2 AD domains in 2 containers
for dc1 its working great as its bridge, but when i try to add dc2 and create the macvlan it seems that the ports dont seem to get opened 
is there a limitation on the docker file?

These were the steps i took

created the docker network

```
sudo docker network create \
        --driver macvlan \
        --subnet 192.168.7.0/24 \
        --gateway 192.168.7.254 \
        --ip-range 192.168.7.100/29 \
        --opt parent=ens18 \
        macvlan_net
```

this is the docker compose of dc2
```

version: "3.1"

services:
  dc2:
    image: samba:ubuntu
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfiles/ubuntu
      args:
        SMB_VERSION: "${SMB_VERSION:-latest}"
    container_name: dc2
    hostname: DC2
    privileged: true
    environment:
      REALM: DGS2.NET
      DOMAIN: DGS2
      ADMIN_PASS: Passw0rd
      DNS_FORWARDER: 8.8.8.8
    networks:
      - macvlan_net
    volumes:
      - dc2-local-samba:/usr/local/samba

networks:
 macvlan_net:
   name: macvlan_net

volumes:
  dc2-local-samba:
```

it seems that in the container it shows the ports running 

![image](https://github.com/diegogslomp/samba-ad-dc/assets/13953629/fef7a571-4ddb-4fbd-a75e-e281c770db1f)

thank you

**Comment by diegogslomp** [comment]
Hello

Check the [docker-compose main file](https://github.com/diegogslomp/samba-ad-dc/blob/master/docker-compose.yml) that creates a multiple DC environment, specifically at the `BIND_NETWORK_INTERFACES: false` option, you only bind interfaces in network host mode. Any trouble let me know.

**Comment by killmasta93** [comment]
thanks for the reply, i was looking at the main file, but it shows dc1 dc2 with the same dgs,net
lets say i want dgs.net and another domain dgs2.net

Thank you

**Comment by diegogslomp** [comment]
Then you need to create two DCs without relation between them, maybe something like this:

```
version: "3.8"

services:
  dc1:
    image: diegogslomp/samba-ad-dc
    restart: unless-stopped
    container_name: dc1
    hostname: DC1
    privileged: true
    environment:
      REALM: DGS.NET
      DOMAIN: DGS
      ADMIN_PASS: Passw0rd
      DNS_FORWARDER: 8.8.8.8
      BIND_NETWORK_INTERFACES: false
    dns_search: dgs.net
    dns:
      - 172.16.238.10
    extra_hosts:
      - "DC1 DC1.dgs.net:172.16.238.10"
    command: bash -c "samba-domain-provision && samba -F"
    volumes:
      - dc1-local-samba:/usr/local/samba
    networks:
      static-network:
        ipv4_address: 172.16.238.10

  dc2:
    image: diegogslomp/samba-ad-dc
    restart: unless-stopped
    container_name: dc2
    hostname: DC2
    privileged: true
    environment:
      REALM: DGS2.NET
      DOMAIN: DGS2
      ADMIN_PASS: Passw0rd
      DNS_FORWARDER: 8.8.8.8
      BIND_NETWORK_INTERFACES: false
    dns_search: dgs2.net
    dns:
      - 172.16.238.20
    extra_hosts:
      - "DC2 DC2.dgs2.net:172.16.238.20"
    command: bash -c "samba-domain-provision && samba -F"
    volumes:
      - dc2-local-samba:/usr/local/samba
    networks:
      static-network:
        ipv4_address: 172.16.238.20

volumes:
  dc1-local-samba:
  dc2-local-samba:

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.16.238.0/24
```

**Comment by killmasta93** [comment]
thank you so much for the reply, the issue is that i need to bind the network such as networkmode to host so when my windows connect to the domain they can connect with no issue showing others IPs

So this is my DC1 and is working perfectly
```

version: "3.1"

services:
  dc1:
    image: samba:ubuntu
    restart: unless-stopped
    network_mode: host
    build:
      context: .
      dockerfile: dockerfiles/ubuntu
      args:
        SMB_VERSION: "${SMB_VERSION:-latest}"
    container_name: dc1
    hostname: DC1
    privileged: true
    environment:
      REALM: DGS.NET
      DOMAIN: DGS
      ADMIN_PASS: Passw0rd
      DNS_FORWARDER: 8.8.8.8
    volumes:
      - dc1-local-samba:/usr/local/samba

volumes:
  dc1-local-samba:
    driver: local-persist
    driver_opts:
     mountpoint: /data2
```

and this is my DC2 which loads buts when i try to nmap the ports its shows that its closed not sure why

```

version: "3.1"

services:
  dc2:
    image: samba:ubuntu
    restart: unless-stopped
#    network_mode: host
    build:
      context: .
      dockerfile: dockerfiles/ubuntu
      args:
        SMB_VERSION: "${SMB_VERSION:-latest}"
    container_name: dc2
    hostname: DC2
    privileged: true
    environment:
      REALM: DGS2.NET
      DOMAIN: DGS2
      ADMIN_PASS: Passw0rd
      DNS_FORWARDER: 8.8.8.8
      BIND_NETWORK_INTERFACES: true
    networks:
      - macvlan_net
    volumes:
      - dc2-local-samba:/usr/local/samba

networks:
 macvlan_net:
   name: macvlan_net

volumes:
  dc2-local-samba:
```

```
docker inspect macvlan_net
[
    {
        "Name": "macvlan_net",
        "Id": "b6cedf582369a8caeeab5cff129d26c8f442006862e637ca79e2c63f657a7fef",
        "Created": "2023-06-11T12:39:21.641386753-05:00",
        "Scope": "local",
        "Driver": "macvlan",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "192.168.7.0/24",
                    "IPRange": "192.168.7.100/29",
                    "Gateway": "192.168.7.254"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "e9da77b07c79c95606d21ba84b41825c1c9d291a18cdc37842f218e4c4b645c7": {
                "Name": "dc2",
                "EndpointID": "5b22dc8903dc74c0341f07de338ca82444117c34f013ae17753ee27bb490fc6f",
                "MacAddress": "02:42:c0:a8:07:60",
                "IPv4Address": "192.168.7.96/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "parent": "ens18"
        },
        "Labels": {}
    }
]
```

on the container of dc2 i can ping the gateway 192.168.7.254 and the windows server 192.168.7.105 no issue and vise versa 

![image](https://github.com/diegogslomp/samba-ad-dc/assets/13953629/61e9c050-ed7b-4f41-b961-27122aecc79e)

```

 nmap 192.168.7.96 -p 53
Starting Nmap 7.80 ( https://nmap.org ) at 2023-06-12 10:53 -05
Nmap scan report for 192.168.7.96
Host is up (0.00012s latency).

PORT   STATE  SERVICE
53/tcp closed domain
MAC Address: 02:42:C0:A8:07:60 (Unknown)

Nmap done: 1 IP address (1 host up) scanned in 0.32 seconds

```

Thank you

**Comment by diegogslomp** [comment]
Hello

When you use network mode, you expose the container ports to the outside of the docker, for example, the dns 53 port of your dc1 can be accessed from the outside, as if the dns server was installed on your host. Since dc2 uses the same ports as dc1, you can only expose one dns service on port 53, for example, to expose another dns 53 you need to shutdown one and start up another.

**Comment by killmasta93** [comment]
Thank you so much for the reply, so i tried with your setup of docker compose, and im getting this error when try to connect to the domain from neither domains 

![image](https://github.com/diegogslomp/samba-ad-dc/assets/13953629/e2712f6b-acb9-4dc3-a7a3-a1a3218d96a7)

![image](https://github.com/diegogslomp/samba-ad-dc/assets/13953629/996ffe70-bbe2-49cc-9ee0-bbaafe13147a)

my linux host ip  

![image](https://github.com/diegogslomp/samba-ad-dc/assets/13953629/fae69100-5b76-4614-87fc-d1e8e7caf924)


i tried nmap the linux host to see if the port is opened and shows closed 

```

nmap 192.168.7.189 -p 88
Starting Nmap 7.80 ( https://nmap.org ) at 2023-06-12 22:15 -05
Nmap scan report for 192.168.7.189
Host is up (0.028s latency).

PORT   STATE  SERVICE
88/tcp closed kerberos-sec

Nmap done: 1 IP address (1 host up) scanned in 0.13 seconds

```

Thank you

**Comment by diegogslomp** [comment]
This is the correct docker compose using network host mode:
```
version: "3.1"

services:
  dc1:
    image: diegogslomp/samba-ad-dc
    restart: unless-stopped
    network_mode: host
    container_name: dc1
    hostname: DC1
    privileged: true
    environment:
      REALM: DGS.NET
      DOMAIN: DGS
      ADMIN_PASS: Passw0rd
      DNS_FORWARDER: 8.8.8.8
    volumes:
      - dc1-local-samba:/usr/local/samba

volumes:
  dc1-local-samba:
```
Change your host `/etc/resolv.conf` updating dns server and nameserver:
```
search dgs.net
nameserver 192.168.7.189
```
Add the host to `/etc/hosts`:
```
127.0.0.1     localhost
192.168.7.189     DC1.dgs.net     DC1
```
More info configuring a domain controller [here](https://wiki.samba.org/index.php/Setting_up_Samba_as_an_Active_Directory_Domain_Controller). Any trouble let me know.

**Comment by killmasta93** [comment]
Thanks for the reply, allright so looking at it again it seems that i need network mode for both of the docker containers 
something like this


![image](https://github.com/diegogslomp/samba-ad-dc/assets/13953629/2fe8071e-4a89-4db1-956b-380fd6542da3)


would your container be compatible something like that? as one container in ens18 network mode host and another ens19 network mode host

**Comment by diegogslomp** [comment]
Two phyisical interfaces, nice, don't know if there is a way to `--network host` each docker to each interface, I'll take a look

**Comment by killmasta93** [comment]
Thank you yeah im trying to look though the docs of docker, but cant seem to find anything, it be very interesting to have varios AD in the same host with multiple NICS

**Comment by diegogslomp** [comment]
Please send the wordpress conf to comparison, if it not use network host mode, the ports should be exposed manually in the compose file, or there is something with interface binding in smb.conf

**Comment by killmasta93** [comment]
sure this is the wordpress

```
version: '3.9'

services:
  # Database
  db3:
    image: mysql:8.0
    volumes:
      - /wordpress3/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: mypass
    networks:
      - macvlan_net
  # phpmyadmin
  phpmyadmin3:
    depends_on:
      - db3
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
     - "8085:80"
    environment:
      PMA_HOST: db3
      MYSQL_ROOT_PASSWORD: mypass
    networks:
      - macvlan_net
  # Wordpress
  wordpress3:
    depends_on:
      - db3
    image: wordpress:latest
    ports:
     - "8086:80"
    restart: always
    volumes:
      - /wordpress3/html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: 192.168.7.96:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: mypass
    networks:
      - macvlan_net

networks:
 macvlan_net:
   name: macvlan_net
volumes:
  db_data:
  html:
```

and created the network 
```

sudo docker network create \
        --driver macvlan \
        --subnet 192.168.7.0/24 \
        --gateway 192.168.7.254 \
        --ip-range 192.168.7.100/29 \
        --opt parent=ens18 \
        macvlan_net
```
