### ISSUE TITLE
Issue on moving data to another Host

### ISSUE THREAD

**Issue by killmasta93** [diegogslomp/samba-ad-dc#15]
HI
Currently trying to migrate my dc1 container to another host but for some reason its not working, not sure what i missed this were the steps i took first

sent the container image to the other host 

`docker save samba:ubuntu | bzip2 | ssh root@192.168.7.249 docker load`
then copy the files in` /var/lib/docker/volumes/samba-ad-dc_dc1-local-samba/_data`
to the host then edit the docker compose

```
version: "3.1"

services:
  dc1:
    image: samba:ubuntu
    restart: unless-stopped
    networks:
      macvlan_net:
        ipv4_address: 192.168.7.206
    build:
      context: .
      dockerfile: dockerfiles/almalinux
      args:
        SMB_VERSION: "${SMB_VERSION:-latest}"
    container_name: dc1
    hostname: DC1
    privileged: true
    environment:
      REALM: SMD.LOCAL
      DOMAIN: SMD
      ADMIN_PASS: Passw0rd
      DNS_FORWARDER: 8.8.8.8
      BIND_NETWORK_INTERFACES: false
    ports:
      - "53:53"
      - "445:445"
    volumes:
      - dc1-local-samba:/usr/local/samba
      - smd:/data2/

volumes:
  dc1-local-samba:
   driver: local-persist
   driver_opts:
     mountpoint: /smd/_data
  smd:
   driver: local-persist
   driver_opts:
     mountpoint: /smd


networks:
 macvlan_net:
   name: macvlan_net
   driver: macvlan
   driver_opts:
      parent: ens18
   ipam:
      config:
        - subnet: "192.168.7.0/24"
          ip_range: "192.168.7.0/24"
          gateway: "192.168.7.254"

```

i tried checking the logs but cant seem to find the logs to see what would be the issue

Thanks
