### ISSUE TITLE
Docker compose instruction help for Primary AD DC and Secondary DC domain Join

### ISSUE THREAD

**Issue by atlury** [diegogslomp/samba-ad-dc#21]
For my primary DC this compose file works good.

```
version: '3'
services:
  samba-ad-dc:
    image: diegogslomp/samba-ad-dc
    container_name: dc1
    hostname: dc1.name.com
    privileged: true
    network_mode: host
    restart: unless-stopped
    environment:
      REALM: 'NAME.COM'
      DOMAIN: 'NAME'
      ADMIN_PASS: 'Passw0rd'
      DNS_FORWARDER: '8.8.8.8'
    volumes:
      - samba-data:/usr/local/samba
      - samba-krb5:/etc/krb5.conf.d
volumes:
  samba-data:
  samba-krb5:
```

Can I use the similar docker compose file without downloading from github to setup secondary dc and join it to primary.  

Will it take dns:, extra_hosts: and command: bash -c "samba-domain-join DC1 && samba -F" options? 

Assuming I use the image from diegogslomp/samba-ad-dc

Thanking you

**Comment by diegogslomp** [comment]
Hello
You can use something like:
```
  dc2:
    image: diegogslomp/samba-ad-dc
    restart: unless-stopped
    container_name: dc2
    hostname: DC2
    privileged: true
    network_mode: host
    environment:
      REALM: NAME.COM
      DOMAIN: NAME
      ADMIN_PASS: Passw0rd
      DNS_FORWARDER: 8.8.8.8
    dns_search: name.com
    dns:
      - 172.16.238.20
      - 172.16.238.10
    extra_hosts:
      - "DC1 DC1.name.com:172.16.238.10"
      - "DC2 DC2.name.com:172.16.238.20"
    command: bash -c "samba-domain-join DC1 && samba -F"
    volumes:
      - samba-data:/usr/local/samba
      - samba-krb5:/etc/krb5.conf.d
volumes:
  samba-data:
  samba-krb5:
```
Any trouble let me know

**Comment by atlury** [comment]
this works. thank you. I am gonna try out now fileshare (domain join as a member) and squid. Ofcourse there is still the rsync script that needs to sync /usr/local/samba/sysvol/ and /usr/local/samba/private/idmap.ldb

**Comment by diegogslomp** [comment]
You can add a cron job in the dc2 for sysvol replication:
```bash
*/5 * * * *   root    /usr/bin/rsync -XAav --delete-after root@dc1:/usr/local/samba/var/locks/sysvol/ /usr/local/samba/var/locks/sysvol/
```
If you can please share the steps for the fileshare that you did/will do. Any trouble let me know.

**Comment by atlury** [comment]
Install debian and do the following (on baremetal or a vm).

Ofcourse make sure the file server vm itself has the correct static ip in /etc/network/interfaces, has correct /etc/hosts and /etc/hostname file as well as /etc/resolv.conf (making it immutable). Have a NTP server or using your main DC as ntp. These are the first things to do. 

Remove sssd and install other packages for Samba:  

```
apt purge sssd
apt-get install winbind libnss-winbind libpam-winbind libpam-krb5 samba
apt-get install cifs-utils krb5-user
```
`mv /etc/samba/smb.conf /etc/samba/smb.conf.backup`

Edit or create new /etc/samba/smb.conf:

```
[global]
    workgroup = NAME
    security = ADS
    realm = NAME.COM
    winbind refresh tickets = Yes
    vfs objects = acl_xattr
    map acl inherit = Yes
    store dos attributes = Yes
    dedicated keytab file = /etc/krb5.keytab
    kerberos method = secrets and keytab
    winbind use default domain = yes
    winbind enum users = yes
    winbind enum groups = yes
    load printers = no
    printing = bsd
    printcap name = /dev/null
    disable spoolss = yes
    idmap config * : backend = autorid
    idmap config * : range = 10000-24999999
    template shell = /bin/bash
    template homedir = /home/%U
    client max protocol = SMB3
         
[shared]
    path = /srv/samba/shared
    public = no
    writable = yes
    guest ok = no
    #valid users = user1,user2,administrator
    #valid users = @HOME\domainusers
    create mask = 0770
    directory mask = 0770
    read only = no
    browseable = yes
    inherit permissions = Yes
    inherit acls = Yes
    inherit owner = Yes

[homes]
   comment = Home Directories
   browseable = no
   read only = no
   create mask = 0700
   directory mask = 0700
   valid users = %S
```

The configuration line "idmap config * : backend = autorid" in a Samba member server smb.conf file specifies the use of the autorid backend for ID mapping. This is an alternative to other ID mapping backends like rid or ad.

Ensure that client max protocol is not set to a value lower than SMB3, as modern Windows clients use newer SMB protocols.

Consider adding vfs objects = acl_xattr under the [global] section for better ACL handling.

Verify the settings for template homedir and template shell for correct home directory and shell for domain users.

Edit /etc/krb5.conf:

```
[libdefaults]
        default_realm = NAME.COM
        dns_lookup_realm = false
        dns_lookup_kdc = true
        ticket_lifetime = 24h
        renew_lifetime = 7d
        forwardable = true
```
Setting Up File Shares. Create the shared directory:

`sudo mkdir -p /srv/samba/shared
`
Before setting permissions ensure you have compat and winbind added to passwd and group along with others

```
passwd:         compat winbind
group:          compat winbind
```

Set the appropriate permissions. Here, we'll give read/write access to the domain users. Adjust the permissions as needed for your scenario:

```
sudo chown -R root:"Domain Users" /srv/samba/shared
#sudo chown root:HOME\domainusers /srv/samba/shared
sudo chmod -R 0770 /srv/samba/shared
```

Addition note:

```
User-Specific Access (%S): Restricts access to individual users based 
on their username matching the share name. 
Commonly used for personal user shares.

Group-Based Access (@VIMTA\domainusers): Allows access to all members 
of a specific group, useful for shares that are intended for broader access
within an organization or a specific set of users.

```
Obtain a Kerberos ticket:

`kinit administrator@HOME.COM`

Join the Samba server to the AD domain:

`sudo net ads join -U administrator`

Restart Samba to apply the changes:

`sudo systemctl restart smbd nmbd winbind`

Verify Domain Membership:
```
wbinfo -u
net ads info
```

Testing File Share Access
From a Windows client in the AD domain, try accessing the shared folder:

`\\samba-server-ip\shared`

Replace samba-server-ip with the actual IP address of your Samba server. This should work on non joined windows clients also. For username and password try in the format below.

```
home.com\administrator
Passw0rd
```

**Comment by atlury** [comment]
Will now get transparent squid working with DC1 docker.

**Comment by killmasta93** [comment]
hi @atlury quick question the samba server for file server is a VM or docker container?

**Comment by atlury** [comment]
Its a seperate VM in debian 12. We can containerize it though. Havent had the time.

**Comment by atlury** [comment]
Btw squid also is working.

**Comment by killmasta93** [comment]
hi @atlury Awesome, Let me know if you able to containerize been trying for a while but i can seem to only connect it though VM

**Comment by atlury** [comment]
Do not use Alpine Linux. It will never work especially when trying to connect or communicate to another samba AD DC since glibc is not available. I think they are communication protocols missing. Debian or ubuntu docker will work.

**Comment by killmasta93** [comment]
hi @atlury so i got finally working in an lxc container proxmox but cant seem to wrap my head how i can deply it on docker container

I was maybe thinking like this but just a theory 
the docker file

```
# Use Ubuntu 23 as the base image
FROM ubuntu:23

# Install necessary packages
RUN apt-get update && \
    apt-get install -y winbind libnss-winbind libpam-winbind libpam-krb5 samba cifs-utils krb5-user && \
    rm -rf /var/lib/apt/lists/*

# Copy Samba and Kerberos configuration files into the container
COPY smb.conf /etc/samba/smb.conf
COPY krb5.conf /etc/krb5.conf
COPY nsswitch.conf /etc/nsswitch.conf
COPY entrypoint.sh /usr/local/bin/entrypoint.sh

# Create necessary directories
RUN mkdir -p /srv/samba/shared

# Set permissions for the shared directory
RUN chown -R root:"Domain Users" /srv/samba/shared && \
    chmod -R 0770 /srv/samba/shared

# Expose Samba ports
EXPOSE 137/udp 138/udp 139 445

# Set entrypoint to start Samba services
ENTRYPOINT ["smbd", "--foreground", "--log-stdout"]



```
the docker compose

```
version: '3.8'

services:
  samba:
    build: .
    container_name: samba-container
    environment:
      SAMBA_ADMIN_USER: administrator
      SAMBA_ADMIN_PASSWORD: ${SAMBA_ADMIN_PASSWORD}    
    volumes:
      - ./smb.conf:/etc/samba/smb.conf
      - ./krb5.conf:/etc/krb5.conf
      - samba-data:/srv/samba/shared
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "445:445"

volumes:
  samba-data:
```

i would use the same smb.conf from the above ex and krb5.conf also with nsswitch.conf


but would create a entry point script

```
#!/bin/bash

# Join the domain
if [ -n "$SAMBA_ADMIN_USER" ] && [ -n "$SAMBA_ADMIN_PASSWORD" ]; then
    echo "$SAMBA_ADMIN_PASSWORD" | kinit "$SAMBA_ADMIN_USER"
    net ads join -U "$SAMBA_ADMIN_USER"%"$SAMBA_ADMIN_PASSWORD"
fi

# Start Samba
exec smbd --foreground --log-stdout

```

then would run this

```
export SAMBA_ADMIN_PASSWORD=yourpassword
docker-compose up -d
```

still havent tried it just a theory going to try it this week to see
