### ISSUE TITLE
Issue installing 

### ISSUE THREAD

**Issue by killmasta93** [diegogslomp/samba-ad-dc#8]
Hi
Currently have an issue with installing the docker container

this is my docker compose
```

version: "3.1"

services:
  dc1:
    image: samba:almalinux
    restart: unless-stopped
    network_mode: host
    build:
      context: .
      dockerfile: dockerfiles/almalinux
    container_name: dc1
    hostname: DC1
    privileged: true
    environment:
      REALM: FIX.LOCAL
      DOMAIN: FIX
      ADMIN_PASS: Passw0rd
      DNS_FORWARDER: 8.8.8.8
    volumes:
      - dc1-local-samba:/usr/local/samba

volumes:
  dc1-local-samba:
   driver: local-persist
   driver_opts:
     mountpoint: /samba

```

currently getting this error on the logs

```
dc1  | /usr/local/sbin/samba-domain-provision: line 22: samba-tool: command not found
dc1  | /usr/local/sbin/samba-domain-provision: line 22: samba-tool: command not found
dc1  | /usr/local/sbin/samba-domain-provision: line 22: samba-tool: command not found
dc1  | /usr/local/sbin/samba-domain-provision: line 22: samba-tool: command not found
dc1  | /usr/local/sbin/samba-domain-provision: line 22: samba-tool: command not found
dc1  | /usr/local/sbin/samba-domain-provision: line 22: samba-tool: command not found
dc1  | /usr/local/sbin/samba-domain-provision: line 22: samba-tool: command not found
dc1  | /usr/local/sbin/samba-domain-provision: line 22: samba-tool: command not found
dc1  | /usr/local/sbin/samba-domain-provision: line 22: samba-tool: command not found
dc1  | /usr/local/sbin/samba-domain-provision: line 22: samba-tool: command not found
dc1  | /usr/local/sbin/samba-domain-provision: line 22: samba-tool: command not found
dc1 exited with code 127
```
Thank you
